INSERT INTO HOTEL.ROOM (hotel_id,room_type,status,extra_bed,extra_bed_price,num_double_bed,num_single_bed,price_per_night,description) VALUES
-- Single Rooms Sydney #15
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'occupied', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'under maintenance', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(1,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
-- Single Rooms Brisbane #15
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'occupied', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'under maintenance', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(2,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
-- Single Rooms Melbourne #15
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'occupied', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'under maintenance', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(3,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
-- Single Rooms Adelaide #15
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'occupied', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'under maintenance', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(4,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
-- Single Rooms Hobart #15
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'occupied', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'under maintenance', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
(5,'Single Room', 'available', false, 0, 0, 1, 70, 'One single bed'),
-- Twin bed Rooms Sydney #10
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(1, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
-- Twin bed Rooms Brisbane #10
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(2, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
-- Twin bed Rooms Melbourne #10
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(3, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
-- Twin bed Rooms Adelaide #10
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(4, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
-- Twin bed Rooms Hobart #10
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
(5, 'Twin Bed', 'available', false, 35, 0, 2, 120, 'Two single beds'),
-- Queen Rooms Sydney #10
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(1, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
-- Queen Rooms Brisbane #10
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(2, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
-- Queen Rooms Melbourne #10
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(3, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
-- Queen Rooms Adelaide #10
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(4, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
-- Queen Rooms Hobart #10
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
(5, 'Queen', 'available', false, 35, 1, 0, 120, 'One double bed'),
-- Executive Rooms Sydney #5
(1, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(1, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(1, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(1, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(1, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
-- Executive Rooms Brisbane #5
(2, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(2, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(2, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(2, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(2, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
-- Executive Rooms Melbourne #5
(3, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(3, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(3, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(3, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(3, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
-- Executive Rooms Adelaide #5
(4, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(4, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(4, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(4, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(4, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
-- Executive Rooms Hobart #5
(5, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(5, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(5, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(5, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
(5, 'Executive', 'available', false, 35, 1, 0, 180, 'One double bed, more facilities than Queen Room'),
-- Suite Rooms Sydney #2
(1, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
(1, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
-- Suite Rooms Brisbane #2
(2, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
(2, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
-- Suite Rooms Melbourne #2
(3, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
(3, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
-- Suite Rooms Adelaide #2
(4, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
(4, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
-- Suite Rooms Hobart #2
(5, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities'),
(5, 'Suite', 'available', false, 35, 2, 0, 300, 'Two double beds, most luxurious facilities');
