SELECT * FROM ROOM WHERE hotel_id=1;

SELECT Type, SUM(Availables) as Availables, Price, Hotel, City
FROM (
SELECT r.room_type as Type, COUNT(r.ROOM_TYPE) as Availables, r.PRICE_PER_NIGHT as Price, h.NAME as hotel, c.NAME as city
FROM ROOM r, ROOM_AVAILABILITY ra, HOTEL h, CITY c
WHERE r.ID = ra.ROOM_ID 
AND (('2014-05-05' < ra.DATE_START)
	OR ('2014-05-03' > ra.DATE_END))
AND r.HOTEL_ID = h.ID
AND h.CITY_ID = c.ID
AND c.ID = 1
AND r.PRICE_PER_NIGHT <= 290
GROUP BY r.ROOM_TYPE, r.PRICE_PER_NIGHT, h.NAME, c.NAME
UNION
SELECT r.ROOM_TYPE as Type, COUNT(r.ROOM_TYPE) as Availables, r.PRICE_PER_NIGHT as Price, h.NAME as hotel, c.Name as city
FROM ROOM r
LEFT JOIN HOTEL h ON h.ID = r.HOTEL_ID
LEFT JOIN CITY c ON c.ID = h.CITY_ID
WHERE r.ID NOT IN (SELECT ID FROM ROOM_AVAILABILITY)
AND c.ID = 1
AND r.PRICE_PER_NIGHT <= 290
GROUP BY r.ROOM_TYPE, r.PRICE_PER_NIGHT, h.NAME, c.NAME
) as avail
GROUP BY Type, Price, Hotel, City
ORDER BY Price;

SELECT r.ROOM_TYPE, COUNT(r.ROOM_TYPE)
FROM ROOM r
WHERE r.HOTEL_ID = 1
GROUP BY r.ROOM_TYPE;

SELECT r.ROOM_TYPE, COUNT(r.ROOM_TYPE) as Availables, h.NAME, c.Name
FROM ROOM r
LEFT JOIN HOTEL h ON h.ID = r.HOTEL_ID
LEFT JOIN CITY c ON c.ID = h.CITY_ID
WHERE r.ID NOT IN (SELECT ID FROM ROOM_AVAILABILITY)
AND c.ID = 1
GROUP BY r.ROOM_TYPE, h.NAME, c.NAME;


SELECT Type, SUM(Availables) as Availables, Price, Hotel, City 
FROM ( 
	SELECT r.room_type as Type, COUNT(r.ROOM_TYPE) as Availables, r.PRICE_PER_NIGHT as Price, h.NAME as hotel, c.NAME as city 
	FROM ROOM r, ROOM_AVAILABILITY ra, HOTEL h, CITY c 
	WHERE r.ID = ra.ROOM_ID  
	AND (('2014-05-12' < ra.DATE_START) 	OR ('2014-05-11' > ra.DATE_END)) 
	AND r.HOTEL_ID = h.ID 
	AND h.CITY_ID = c.ID 
	AND c.ID = 1 
	AND r.PRICE_PER_NIGHT <= 305 
	GROUP BY r.ROOM_TYPE, r.PRICE_PER_NIGHT, h.NAME, c.NAME 
	UNION SELECT r.ROOM_TYPE as Type, COUNT(r.ROOM_TYPE) as Availables, r.PRICE_PER_NIGHT as Price, h.NAME as hotel, c.Name as city FROM ROOM r LEFT JOIN HOTEL h ON h.ID = r.HOTEL_ID LEFT JOIN CITY c ON c.ID = h.CITY_ID WHERE r.ID NOT IN (SELECT ID FROM ROOM_AVAILABILITY) AND c.ID = 1 AND r.PRICE_PER_NIGHT <= 305 GROUP BY r.ROOM_TYPE, r.PRICE_PER_NIGHT, h.NAME, c.NAME ) as avail GROUP BY Type, Price, Hotel, City ORDER BY Price
